services:
  app:
    build: .
    ports:
      - "127.0.0.1:3001:3000"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: miniapp
    depends_on:
      - db
    volumes:
      - ./src:/app

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: miniapp
    volumes:
      - miniapp-mysql-data:/var/lib/mysql

volumes:
  miniapp-mysql-data:

